apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/orderdb
            - name: SPRING_DATASOURCE_USERNAME
              value: orderuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: orderpass
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-0.kafka:9092
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.kafka.bootstrap-servers":"kafka-0.kafka:9092"}'
            - name: TZ
              value: Asia/Kolkata
