spring:
  application:
    name: restaurant.service

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdb
    username: restaurant
    password: restaurantpass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      data-source-properties:
        stringtype: unspecified
      connection-init-sql: SET TIME ZONE 'Asia/Kolkata';

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
    show-sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

server:
  port: 8081

# ðŸ‘‡ Add this line
spring.jackson.time-zone: Asia/Kolkata
